	@startuml
actor client
box "selenium-remote-driver" #LightBlue
	participant DesiredCapabilities as capabilities
	participant RemoteWebDriver
	participant HttpCommandExecutor
	participant ProtocolHandshake
end box

box "selenium-chrome-driver" #DeepSkyBlue
	participant ChromeDriver
	participant ChromeDriverService
	participant ChromeDriverCommandExecutor
end box

== Prepare browser capabilities ==
client -> capabilities : chrome()
capabilities -> client : capabilities object
== Prepare driver ==
client -> ChromeDriver : ::new(capabilities)
activate ChromeDriver
ChromeDriver -> ChromeDriverService : createDefaultService()
note right : In this configuration, the service will use the chromedriver executable identified by the\n {@link #CHROME_DRIVER_EXE_PROPERTY} system property. Each service created by this method will\nbe configured to use a free port on the current system.
activate ChromeDriverService
ChromeDriverService -> ChromeDriver : chromeDriverService
deactivate ChromeDriverService
ChromeDriver -> ChromeDriverCommandExecutor : ::new(chromeDriverService)
activate ChromeDriverCommandExecutor
ChromeDriverCommandExecutor -> ChromeDriver : commandExecutor
deactivate ChromeDriverCommandExecutor
ChromeDriver -> RemoteWebDriver : ::new(commandExecutor, capabilities)
activate RemoteWebDriver
RemoteWebDriver -> RemoteWebDriver : init(capabilities)
RemoteWebDriver -> RemoteWebDriver : startSession(capabilities)
activate RemoteWebDriver #FFBBBB
RemoteWebDriver -> ChromeDriverCommandExecutor : execute(DriverCommand.NEW_SESSION)
activate ChromeDriverCommandExecutor #FFBBBB
ChromeDriverCommandExecutor -> ChromeDriverService : start()
ChromeDriverCommandExecutor -> HttpCommandExecutor : execute(DriverCommand.NEW_SESSION)
activate HttpCommandExecutor #FFBBBB
HttpCommandExecutor -> ProtocolHandshake : createSession(command)
activate ProtocolHandshake #FFBBBB
ProtocolHandshake -> ProtocolHandshake : HTTP POST /session
ProtocolHandshake -> HttpCommandExecutor : result
deactivate ProtocolHandshake
HttpCommandExecutor -> ChromeDriverCommandExecutor : Result
deactivate ChromeDriverCommandExecutor
deactivate ProtocolHandshake
deactivate HttpCommandExecutor

RemoteWebDriver -> ChromeDriver
deactivate RemoteWebDriver
ChromeDriver -> client : driver
deactivate ChromeDriver

@enduml

@startuml
'Capability hierarchy
package selenium-api <<Rectangle>> {
	interface Capabilities
	class AbstractCapabilities
	class ImmutableCapabilities
	class MutableCapabilities
}

package selenium-chrome-driver <<Rectangle>> {
	class ChromeOptions
}

package selenium-remote-driver <<Rectangle>> {
	class DesiredCapabilities
}

interface Serializable

Capabilities <|.down. AbstractCapabilities
Serializable <|.down. MutableCapabilities
Serializable <|.down. ImmutableCapabilities
AbstractCapabilities <|-down- MutableCapabilities
AbstractCapabilities <|-down- ImmutableCapabilities
MutableCapabilities <|-down- DesiredCapabilities
MutableCapabilities <|-down- ChromeOptions
@enduml





@startuml
' Driver classes hierarchy
package selenium-api <<Rectangle>> {
	interface SearchContext
	interface WebDriver
}
package selenium-remote-driver <<Rectangle>> {
	class RemoteWebDriver
}
package selenium-chrome-driver <<Rectangle>> {
	class ChromeDriver
}

SearchContext <.up. WebDriver
WebDriver <-up- RemoteWebDriver
RemoteWebDriver <-up- ChromeDriver
@enduml







@startuml
' overview of component communication for UI testing
node "ChromeDriver" as driver
[Selenium client library] -> driver : HTTP Request
note bottom of driver
implements WebDriver protocol
HttpServer in C++
end note
cloud "Browser" as browser
driver - debug_port : send commands
note bottom of debug_port
DevTools
remote debugging
interface
end note
debug_port -> browser : WebSocket
@enduml




@startuml
' DriverService classes hierarchy
package selenium-remote-driver <<Rectangle>> {
	class DriverService
	note left of DriverService
    Manages the life and death of a native executable driver server.

    It is expected that the driver server implements the
    WebDriver W3C protocol (it was JsonWireProtocol before standartization)

    In particular, it should implement /status command that is used to check if the server is alive.

    In addition to this, it is supposed that the driver server implements /shutdown hook that is
    used to stop the server.
    end note
}
package selenium-chrome-driver <<Rectangle>> {
	class ChromeDriverService
}
package selenium-firefox-driver <<Rectangle>> {
	class GeckoDriverService
}
DriverService <|-down- ChromeDriverService
DriverService <|-down- GeckoDriverService
@enduml






@startuml
' CommandExecutor classes hierarchy
package selenium-remote-driver <<Rectangle>> {
	interface CommandExecutor {
		Response execute(Command command)
	}
	class HttpCommandExecutor
	class DriverCommandExecutor
	note left of DriverCommandExecutor
		A specialized HttpCommandExecutor that will use a DriverService
		that lives and dies with a single WebDriver session.
		The service will be restarted upon each new session
		request and shutdown after each quit command.
	end note
	class DriverService

}
package selenium-chrome-driver <<Rectangle>> {
	class ChromeDriverCommandExecutor
		note left of ChromeDriverCommandExecutor
    		understands ChromeDriver specific commands
    		List of ChromeWebdriver commands:
    		https://chromium.googlesource.com/chromium/src/+/master/chrome/test/chromedriver/client/command_executor.py
    	end note
}
CommandExecutor <|.down. HttpCommandExecutor
HttpCommandExecutor <|-down- DriverCommandExecutor
DriverService *-left- DriverCommandExecutor
DriverCommandExecutor <|-down- ChromeDriverCommandExecutor
@enduml

@startuml
' CommandCodec classes hierarchy
package selenium-remote-driver <<Rectangle>> {
	interface CommandCodec
	note left of CommandCodec
		Converts Command objects to and from another representation.
	end note
	class AbstractHttpCommandCodec
	note left of AbstractHttpCommandCodec
    	Adheres to the W3C's WebDriver wire protocol
    	https://w3.org/tr/webdriver
    end note
    class JsonHttpCommandCodec
    note bottom of JsonHttpCommandCodec
		Adheres to the Selenium project's JSON/HTTP wire protocol
		https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol
		Should be deprecated
	end note
   class W3CHttpCommandCodec
    note bottom of W3CHttpCommandCodec
		Adheres to the W3C's WebDriver wire protocol
		https://w3.org/tr/webdriver
	end note

}
CommandCodec <|.down. AbstractHttpCommandCodec
AbstractHttpCommandCodec <|-down- JsonHttpCommandCodec
AbstractHttpCommandCodec <|-down- W3CHttpCommandCodec
@enduml

